version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Saym7296
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: saym
      MYSQL_PASSWORD: Saym7296
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql_db
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Saym7296
    ports:
      - "8080:80"

volumes:
  mysql_data:
