# Generated by Django 5.1.4 on 2024-12-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name',
        ),
    ]
