# Generated by Django 5.1.4 on 2024-12-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
    ]
