# Generated by Django 5.1.4 on 2024-12-04 19:39

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_customuser_age_customuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('UUID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('social_media', models.CharField(choices=[('L', 'LinkedIn'), ('G', 'GitHub'), ('F', 'Facebook')], max_length=1, verbose_name='Social Media')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('user', models.ManyToManyField(related_name='social_media', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Social Media',
                'verbose_name_plural': 'User Social Media',
            },
        ),
    ]
