# Generated by Django 5.1.4 on 2024-12-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_usersocialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSocialMedia',
        ),
    ]
